export const SET_IS_LOADING = "SET_IS_LOADING";
export const REQUEST_SIGNUP = "REQUEST_SIGNUP";
export const SUCCESS_SIGNUP = "SUCCESS_SIGNUP";
export const FAILED_SIGNUP = "FAILED_SIGNUP";

export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const FAILED_LOGIN = "FAILED_LOGIN";

export const REQUEST_LOGOUT = "REQUEST_LOGOUT";
